name: ${project.name}
main: de.themoep.specialitems.SpecialItems
version: '${minecraft.plugin.version}'
description: ${project.description}
authors: [Phoenix616]
commands:
   specialitems:
      aliases: [skullitem]
      description: Command description.
      usage: /<command> list|info|get|set|reload
      permission: specialitems.command
      permission-message: You don't have the permission <permission>
permissions:
   specialitems.command:
      description: Gives permission to the plugin command
      default: op
   specialitems.command.list:
      description: Gives permission to the plugin command
      default: op
   specialitems.command.get:
      description: Gives permission to the plugin command
      default: op
   specialitems.command.get.others:
      description: Gives permission to the plugin command
      default: op
   specialitems.command.set:
      description: Gives permission to the plugin command
      default: op
   specialitems.command.reload:
      description: Gives permission to the plugin command
      default: op